# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

elogLik <- function(model, data, min, max, breaks) {
    .Call('EMdevs_elogLik', PACKAGE = 'EMdevs', model, data, min, max, breaks)
}

crisp <- function(n, tsac = 250, N = 11, m_lab = 180, sd_lab = 45, m_nlab = 40, sd_nlab = 10, m_ex = 40, sd_ex = 13) {
    .Call('EMdevs_crispR', PACKAGE = 'EMdevs', n, tsac, N, m_lab, sd_lab, m_nlab, sd_nlab, m_ex, sd_ex)
}

